IF OBJECT_ID('dbo.UserTitles', 'U') IS NOT NULL DROP TABLE dbo.UserTitles;
IF OBJECT_ID('dbo.TitleGenres', 'U') IS NOT NULL DROP TABLE dbo.TitleGenres;
IF OBJECT_ID('dbo.Genres', 'U') IS NOT NULL DROP TABLE dbo.Genres;
IF OBJECT_ID('dbo.Titles', 'U') IS NOT NULL DROP TABLE dbo.Titles;
IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL DROP TABLE dbo.Users;

CREATE TABLE dbo.Users (
  UserId INT IDENTITY(1,1) PRIMARY KEY,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Titles (
  TitleId INT IDENTITY(1,1) PRIMARY KEY,
  Title NVARCHAR(200) NOT NULL,
  TitleType NVARCHAR(20) NOT NULL CHECK (TitleType IN ('Movie','Series')),
  ReleaseYear INT NOT NULL,
  PosterPath NVARCHAR(400) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Genres (
  GenreId INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE dbo.TitleGenres (
  TitleId INT NOT NULL,
  GenreId INT NOT NULL,
  PRIMARY KEY (TitleId, GenreId),
  CONSTRAINT FK_TitleGenres_Title FOREIGN KEY (TitleId) REFERENCES dbo.Titles(TitleId) ON DELETE CASCADE,
  CONSTRAINT FK_TitleGenres_Genre FOREIGN KEY (GenreId) REFERENCES dbo.Genres(GenreId) ON DELETE CASCADE
);

CREATE TABLE dbo.UserTitles (
  UserTitleId INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  TitleId INT NOT NULL,
  Status NVARCHAR(20) NOT NULL CHECK (Status IN ('watchlist','watched')),
  Rating INT NULL CHECK (Rating BETWEEN 1 AND 10),
  Review NVARCHAR(800) NULL,
  WatchedAt DATE NULL,
  IsFavorite BIT NOT NULL DEFAULT 0,
  AddedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_UserTitles_User FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId) ON DELETE CASCADE,
  CONSTRAINT FK_UserTitles_Title FOREIGN KEY (TitleId) REFERENCES dbo.Titles(TitleId) ON DELETE CASCADE,
  CONSTRAINT UQ_UserTitles UNIQUE (UserId, TitleId)
);